import "@/styles/globals.css";

import { type Metadata } from "next";

import fonts from "@/lib/fonts";
import { isRtl } from "@/lib/utils";

import AppProviders from "@/components/providers/app-providers";

const fontsVariables = fonts.map((font) => font.variable);

export const metadata: Metadata = {
  title: "Nextube",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html
      lang={locale}
      dir={isRtl(locale) ? "rtl" : "ltr"}
      className={`${fontsVariables.join(" ")} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <AppProviders locale={locale}>{children}</AppProviders>
      </body>
    </html>
  );
}
